[package]
name = "kube-client-ext"
version = "0.0.37"
edition = "2021"
license = "Apache-2.0"
repository = "https://gitlab.com/imp/kube-client-ext-rs"
description = "Extension trait (helpers) for kube::Client"


[dependencies]
async-trait = "0.1"
k8s-openapi = { version = "0.23", features = [] }
k8s-openapi-ext = "0.0.37"
kube-client = "0.95"


[dev-dependencies.k8s-openapi]
version = "0.23"
features = ["latest"]


[features]
default = ["k8s-openapi/latest"]


[package.metadata.docs.rs]
features = ["k8s-openapi/latest"]
