[package]
name = "kube-client-ext"
version = "0.0.7"
edition = "2021"
license = "Apache-2.0"
repository = "https://gitlab.com/imp/kube-client-ext-rs"
description = "Extension trait (helpers) for kube::Client"


[dependencies]
async-trait = "0.1"
k8s-openapi = { version = "0.16", features = [] }
k8s-openapi-ext = "0.0.8"
kube-client = "0.75"


[dev-dependencies.k8s-openapi]
version = "0.16"
features = ["v1_24"]


[features]
default = ["k8s-openapi/v1_24"]


[package.metadata.docs.rs]
features = ["k8s-openapi/v1_24"]
