[package]
name = "kube-client-ext"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://gitlab.com/imp/kube-client-ext-rs"
description = "Extension trait (helpers) for kube::Client"


[dependencies]
k8s-openapi = { version = "0.15", features = [] }
k8s-openapi-ext = "0.0.3"
kube = { version = "0.74", default-features = false, features = ["client"] }


[dev-dependencies.k8s-openapi]
version = "0.15"
features = ["v1_24"]


[package.metadata.docs.rs]
features = ["k8s-openapi/v1_24"]
