[package]
name = "kube-client-ext"
version = "0.0.24"
edition = "2021"
license = "Apache-2.0"
repository = "https://gitlab.com/imp/kube-client-ext-rs"
description = "Extension trait (helpers) for kube::Client"


[dependencies]
async-trait = "0.1"
k8s-openapi = { version = "0.19", features = [] }
k8s-openapi-ext = "0.0.25"
kube-client = "0.85"


[dev-dependencies.k8s-openapi]
version = "0.19"
features = ["v1_27"]


[features]
default = ["k8s-openapi/v1_27"]


[package.metadata.docs.rs]
features = ["k8s-openapi/v1_27"]
